In [1]:
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [2]:
dataset=loadtxt('marks.csv',delimiter=',')

In [3]:
print(dataset)

[[89. 90. 76. 90. 78.  1.]
 [78. 78. 30. 45. 32.  0.]
 [89. 70. 90. 80. 56.  1.]
 [65. 70. 45. 90. 76.  1.]
 [32. 50. 45. 60. 32.  0.]
 [89. 90. 78. 56. 75.  1.]
 [45. 50. 67. 78. 54.  1.]
 [90. 78. 45. 56. 65.  1.]
 [23. 34. 45. 37. 28.  0.]
 [56. 78. 60. 90. 67.  1.]]


In [4]:
x=dataset[:,0:5]
y=dataset[:,5] 

In [5]:
model=Sequential()
model.add(Dense(512, input_dim=5,activation='sigmoid'))
model.add(Dense(512,activation='sigmoid'))
model.add(Dense(512,activation='sigmoid'))
model.add(Dense(1,activation='softmax'))

In [6]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [7]:
model.fit(x, y, epochs=150, batch_size=10)

Epoch 1/150
10/10 [==============================] - 14s 1s/step - loss: 4.6000 - accuracy: 0.7000
Epoch 2/150
10/10 [==============================] - 0s 2ms/step - loss: 4.6000 - accuracy: 0.7000
Epoch 3/150
10/10 [==============================] - 0s 3ms/step - loss: 4.6000 - accuracy: 0.7000
Epoch 4/150
10/10 [==============================] - 0s 2ms/step - loss: 4.6000 - accuracy: 0.7000
Epoch 5/150
10/10 [==============================] - 0s 2ms/step - loss: 4.6000 - accuracy: 0.7000
Epoch 6/150
10/10 [==============================] - 0s 3ms/step - loss: 4.6000 - accuracy: 0.7000
Epoch 7/150
10/10 [==============================] - 0s 3ms/step - loss: 4.6000 - accuracy: 0.7000
Epoch 8/150
10/10 [==============================] - 0s 3ms/step - loss: 4.6000 - accuracy: 0.7000
Epoch 9/150
10/10 [==============================] - 0s 2ms/step - loss: 4.6000 - accuracy: 0.7000
Epoch 10/150
10/10 [==============================] - 0s 3ms/step - loss: 4.6000 - accuracy: 0.7000
Epoch 11/

In [8]:
_, accuracy = model.evaluate(x, y)
print('Accuracy: %.2f' % (accuracy*100))

10/10 [==============================] - 0s 2ms/step
Accuracy: 70.00
